### ISSUE TITLE
Do we need to timestamp our assets?

### ISSUE THREAD

**Issue by zduci** [thebeansgroup/mail_pipes#15]
Middleman uses a pipeline step called `:asset_hash`, however the final emails don't seem to use this. Since we are moving away from middleman do we want/need this feature?

@luxerama @adtaylor

**Comment by adtaylor** [comment]
Doesn't matter a great deal. I guess it depends how much the assets will change.

**Comment by luxerama** [comment]
@zduci do you know what its used for at the moment? If we get rid of it what happens?

**Comment by zduci** [comment]
@luxerama it's not being used at the moment, if we remove it nothing will change

**Comment by luxerama** [comment]
:+1:
