### ISSUE TITLE
Do we need to use frontmatter variables at the top of files?

### ISSUE THREAD

**Issue by zduci** [thebeansgroup/mail_pipes#16]
Some layouts define variables at the top. They are then used in partials like this `current_page.data.var_name` or just the variable name: https://github.com/thebeansgroup/email_transactional/blob/master/source/partials/blocks/_social_ad.html.erb#L45 . Do we want to be able to use both?

@luxerama @adtaylor

**Comment by adtaylor** [comment]
As Middleman doesn't really have a controller global variables are a huge pain. If we are moving to a new system we could either set as app config variables.

**Comment by zduci** [comment]
@adtaylor that sounds like a good idea, let's do that
