### ISSUE TITLE
How do we include partials?

### ISSUE THREAD

**Issue by zduci** [thebeansgroup/mail_pipes#17]
We need a way to include partials. Middleman uses a method called `partial`, should we implement something similar?

@luxerama @adtaylor

**Comment by luxerama** [comment]
@zduci doesn't activeview have that functionality already?

**Comment by luxerama** [comment]
https://github.com/rails/rails/blob/master/actionview/lib/action_view/renderer/partial_renderer.rb#L32-L282

**Comment by zduci** [comment]
@luxerama yes but the syntax is different:

```
<%= render partial: "account", locals: { account: @buyer } %>
```

vs

```
<%= partial "account" %>
```

**Comment by luxerama** [comment]
@zduci not sure I understand the issue. Sure the syntax is different, but why is that a problem?

**Comment by zduci** [comment]
@luxerama it's not a problem, more a question of which syntax we want to use

**Comment by luxerama** [comment]
@zduci I would prefer it if the syntax is identical to what we have in our other projects (if possible). My guess is that activeview is the same, is that correct?

**Comment by zduci** [comment]
@luxerama yes activeview uses this syntax which we use everywhere else

```
<%= render partial: "account", locals: { account: @buyer } %>
```

i would also use this for consistency
