### ISSUE TITLE
Replace middleman with a custom pipeline

### ISSUE THREAD

**Issue by zduci** [thebeansgroup/mail_pipes#22]

**Comment by adtaylor** [comment]
It's worth noting that we're using a forked premailer - `gem "premailer", github: "thebeansgroup/premailer", branch: "feature/nokogiri-url-removal"`

**Comment by zduci** [comment]
@adtaylor i noticed that but there's no way of declaring the source of the gem in gemspecs. maybe we could define the version as a hash? i'll look into it

/cc @luxerama

**Comment by luxerama** [comment]
@zduci we are going to have to start publishing our own GEMs. I started however had to stop as there was a problem on Travis.

**Comment by luxerama** [comment]
However it would be easier if we could use SHAs

**Comment by zduci** [comment]
@luxerama We can't use SHAs

**Comment by luxerama** [comment]
:-1:
