### ISSUE TITLE
Will FE still be able to develop the emails locally 'live' in the browser as we can in current system?

### ISSUE THREAD

**Issue by adtaylor** [thebeansgroup/mail_pipes#25]

**Comment by zduci** [comment]
@adtaylor I will provide a rack server to serve the emails and will use https://github.com/guard/guard-livereload to refresh the browser when the views change. Is this functionality what you are looking for?

/cc @luxerama

**Comment by adtaylor** [comment]
@zduci Cheers. No need for livereload, I'm not so precious that I don't want to hit cmd+r yet. Rack server will do me just fine :+1:

**Comment by zduci** [comment]
@adtaylor :ok_hand:
