### ISSUE TITLE
Do we want the ability to use different layouts?

### ISSUE THREAD

**Issue by zduci** [thebeansgroup/mail_pipes#34]
At the moment we only seem to use one

@adtaylor @luxerama

**Comment by luxerama** [comment]
@zduci I don't think i fully understand. What templates are you talking about?

**Comment by zduci** [comment]
@luxerama Sorry I meant layouts not templates

**Comment by zduci** [comment]
@luxerama We are using this layout https://github.com/thebeansgroup/email_transactional/blob/master/source/layouts/layout.erb

**Comment by luxerama** [comment]
@zduci gotcha. Yeah, we'll want different layouts. Is that an issue?

**Comment by zduci** [comment]
@luxerama Not an issue

**Comment by luxerama** [comment]
:+1:
