### ISSUE TITLE
Using a service to compile messages to be sent

### ISSUE THREAD

**Issue by luxerama** [thebeansgroup/mail_pipes#6]
We need to be able to have a repository of emails that are sent in multiple different languages preferably with customised content in the future.

Lets discuss approaches.
## Questions we need answers to:
- [x] Which compilation approach are we going to take?
- [ ] How are we going to make this API available to the consumers?
- [ ] How do we cache/share the compiled templates?

CC/ @thebeansgroup/backend @thebeansgroup/frontend

**Comment by zduci** [comment]
we could use one email template and send localised params to it

**Comment by serenbean** [comment]
That's how it works right now. There are `en-GB` and `de` under locales.

**Comment by luxerama** [comment]
My suggestion is we don't use any of the template functionality on the ESPs but use this project to compile the emails to then be sent via the ESP.

**Comment by adtaylor** [comment]
Yep, I kind of built this project to allow us to just send the data to it and it return an email. check out `example_data`

**Comment by zduci** [comment]
Yeah that's what i meant, translate the email first, compile it and send it to the esp

**Comment by luxerama** [comment]
I think one other thing that we should consider is how we are going to manage and track unsubscribes.

**Comment by zduci** [comment]
I think we should make the API available as a gem and store the templates in memcached. @luxerama thoughts?

**Comment by zduci** [comment]
The only client which would use this at the moment is `scripts`.

**Comment by zduci** [comment]
we could even use a webhook with an sqs queue to trigger rebuilding the templates

**Comment by luxerama** [comment]
@adtaylor if I recall correctly you recently raised a valid question. Are we going to need to support hexjam emails. I have spawned another discussion in #23
