### ISSUE TITLE
Benchmark which method is better for processing emails

### ISSUE THREAD

**Issue by zduci** [thebeansgroup/mail_pipes#7]
2 step - compile one template + translate text and replace dynamic params at runtime
3 step - compile different templates for each language + replace dynamic params at runtime

**Comment by zduci** [comment]
Running a simple benchmark it looks like the 3 step is slightly faster, but it's quite close:
https://gist.github.com/zduci/5c59a932a9091c4e64a4

**Comment by luxerama** [comment]
| Steps: | 2 | 3 |
| --- | --- | --- |
| Time: | 13.906244 | 10.341554 |

@zduci I know we are backend engineers, but come on. A bit of pride in your results

**Comment by luxerama** [comment]
@thebeansgroup/backend & @adtaylor I think we should go with the 3 step process given the above numbers.

**Comment by zduci** [comment]
3 step process it is!
