### ISSUE TITLE
API

### ISSUE THREAD

**Issue by luxerama** [thebeansgroup/mail_pipes#8]
Define the full set of API capabilities.

For example:
## Using templates

``` ruby
Email::Transactional.get('reengagement', 'en-GB').populate(
  name: 'Vincent',
  offers: [{title: 'offer 1'}]
)
```
## Compiling templates

Compilation should be used when developing, caching or prewarming the cache.

``` ruby
Email::Transactional.rebuild('reengagement', 'en-GB')
Email::Transactional.rebuild('reengagement') # rebuilds for all locales
Email::Transactional.rebuild # rebuilds all
```

**Comment by luxerama** [comment]
@thebeansgroup/backend @thebeansgroup/email does this look alright?

**Comment by serenbean** [comment]
Different emails might have more dynamic fields, so shall we pass in those as `params` hash perhaps?

**Comment by luxerama** [comment]
@serenbean do you mean this?

```
Email::Transactional.get('reengagement--inline').populate(
  locale: 'en-GB',
  name: 'Vincent',
  offers: [{title: 'offer 1'}]
)
```

**Comment by serenbean** [comment]
yeah I was referring to `name` and `offers` in that

**Comment by luxerama** [comment]
So we could do:

```
Email::Transactional.get('reengagement--inline', 'en-GB').populate do
  name: 'Vincent',
  offers: [{title: 'offer 1'}]
end
```

**Comment by luxerama** [comment]
Then you can have a DynamicFields Object for each email which you can build/validate with the provided Proc

**Comment by serenbean** [comment]
that looks good, since you will always need locale

**Comment by zduci** [comment]
Thinking about how to validate the which fields are needed to each template. We could have a step in the compiling pipeline which parses the template and extracts these fields

**Comment by luxerama** [comment]
@zduci I like it, but also don't like it at the same time. It means that our emails could break because we added some fields to the template without realising the ramifications.

**Comment by zduci** [comment]
@luxerama hmm yes i agree. the emails could break at some point anyway if we validate the params though?

**Comment by luxerama** [comment]
@zduci no, what breaks is the email, not the email creation. However should you change the required params for an email you should be aware that those changes are going to require you to change the consumers to reflect that change.

**Comment by zduci** [comment]
@luxerama i understand that, we wouldn't want to break the emails because the template expects new params. but if we validate the params, the email could break if they are invalid. the only validations i can think of are presence of params and array validations. what sort of validations were you thinking of?

**Comment by luxerama** [comment]
@zduci yeah, just simple rails validations.

**Comment by zduci** [comment]
@luxerama we can't pass in blocks which look like this

``` ruby
Email::Transactional.get('reengagement--inline').populate do
  locale: 'en-GB',
  name: 'Vincent',
  offers: [{title: 'offer 1'}]
end
```

We could pass in a hash:

``` ruby
Email::Transactional.get('reengagement--inline').populate do
  { locale: 'en-GB',
    name: 'Vincent',
    offers: [{title: 'offer 1'}] }
end
```

Or do black ruby magic:

``` ruby
Email::Transactional.get('reengagement--inline').populate do
  locale 'en-GB'
  name 'Vincent'
  offers [{title: 'offer 1'}]
end
```

**Comment by zduci** [comment]
i actually managed to get the last one working using `method_missing` and `instance_exec`

**Comment by zduci** [comment]
@luxerama hmm don't think we need to retrieve a template in order to rebuild it:

``` ruby
Email::Transactional.get('reengagement--inline').rebuild_for('en-GB')
```

I would do this instead:

``` ruby
Email::Transactional.rebuild('reengagement--inline', 'en-GB')
Email::Transactional.rebuild('reengagement--inline') # rebuilds for all locales
```

**Comment by luxerama** [comment]
@zduci sure, makes more sense

**Comment by zduci** [comment]
@luxerama cool :ok_hand:

**Comment by zduci** [comment]
@luxerama you can't specify which file to compile with middleman, it always builds all the pages. this shouldn't be a problem thought because it's fast and we would rarely need to rebuild. I suggest we just use:

``` ruby
 Email::Transactional.rebuild
```

**Comment by zduci** [comment]
@luxerama Now that we are getting rid of middleman we can rebuild individual emails  if we want. I suggest we go back to using:

```
Email::Transactional.rebuild('reengagement--inline', 'en-GB')
Email::Transactional.rebuild('reengagement--inline') # rebuilds for all locales
```

**Comment by luxerama** [comment]
@zduci makes sense. converting to enhancement.

**Comment by zduci** [comment]
:ok_hand:
